<a href="https://colab.research.google.com/github/Swikruti23/Lab-1/blob/main/Swikruti_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_string = "Hello, World"

# split() - Split a string into a list of substrings
words = my_string.split(", ")
print(words) # Output: ['Hello', 'World']

# join() - Join a list of strings into a single string
joined_string = "-".join(words)
print(joined_string) # Output: 'Hello-World'

# strip() - Remove leading and trailing whitespace
trimmed_string = my_string.strip()
print(trimmed_string) # Output: 'Hello, World'

# replace() - Replace a substring with another string
new_string = my_string.replace("World", "Python")
print(new_string) # Output: 'Hello, Python'

# find() - Find the index of a substring
index = my_string.find("World")
print(index) # Output: 7


['Hello', 'World']
Hello-World
Hello, World
Hello, Python
7


In [2]:
my_list = [1, 2, 3]

# append() - Add an element to the end of the list
my_list.append(4)
print(my_list) # Output: [1, 2, 3, 4]

# remove() - Remove the first occurrence of a value
my_list.remove(2)
print(my_list) # Output: [1, 3, 4]

# pop() - Remove and return an element by index
popped_value = my_list.pop(0)
print(popped_value) # Output: 1

# sort() - Sort the list
my_list.sort()
print(my_list) # Output: [3, 4]

# extend() - Append elements from another list
other_list = [5, 6]
my_list.extend(other_list)
print(my_list) # Output: [3, 4, 5, 6]

[1, 2, 3, 4]
[1, 3, 4]
1
[3, 4]
[3, 4, 5, 6]


In [3]:
my_tuple = (1, 2, 2, 3, 4, 2)

# count() - Count the number of occurrences of a value
count_of_2 = my_tuple.count(2)
print(count_of_2)  # Output: 3

# index() - Find the index of a value
index_of_3 = my_tuple.index(3)
print(index_of_3)  # Output: 3

# len() - Get the length of the tuple
length = len(my_tuple)
print(length)  # Output: 6

# max() - Find the maximum value
maximum = max(my_tuple)
print(maximum)  # Output: 4

# min() - Find the minimum value
minimum = min(my_tuple)
print(minimum)  # Output: 1

3
3
6
4
1


In [4]:
my_set1 = {1, 2, 3}
my_set2 = {3, 4, 5}

# add() - Add an element to the set
my_set1.add(4)
print(my_set1) # Output: {1, 2, 3, 4}

# remove() - Remove an element from the set
my_set1.remove(2)
print(my_set1) # Output: {1, 3, 4}

# union() - Create a new set containing unique elements from two sets
union_set = my_set1.union(my_set2)
print(union_set) # Output: {1, 3, 4, 5}

# intersection() - Create a new set containing common elements
intersection_set = my_set1.intersection(my_set2)
print(intersection_set) # Output: {3, 4}

# difference() - Create a new set with elements in the first set but not the second
difference_set = my_set1.difference(my_set2)
print(difference_set) # Output: {1}

{1, 2, 3, 4}
{1, 3, 4}
{1, 3, 4, 5}
{3, 4}
{1}


In [5]:
my_dict = {"name": "Alice", "age": 30, "city": "New York"}

# keys() - Get a list of keys
keys = my_dict.keys()
print(keys) # Output: dict_keys(['name', 'age', 'city'])

# values() - Get a list of values
values = my_dict.values()
print(values) # Output: dict_values(['Alice', 30, 'New York'])

# items() - Get a list of key-value pairs as tuples
items = my_dict.items()
print(items) # Output: dict_items([('name', 'Alice'), ('age', 30), ('city', 'New York')])

# get() - Get the value associated with a key
age = my_dict.get("age")
print(age) # Output: 30

# pop() - Remove and return the value associated with a key
city = my_dict.pop("city")
print(city) # Output: 'New York'

dict_keys(['name', 'age', 'city'])
dict_values(['Alice', 30, 'New York'])
dict_items([('name', 'Alice'), ('age', 30), ('city', 'New York')])
30
New York


In [6]:
string_A ="Hello"
string_B ="World"
reversed_string_A = string_A[::-1]
result = reversed_string_A + string_B
print(result)

olleHWorld


In [7]:
work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'), ('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]

def find_female_with_most_hours(work_hours):
    max_hours = 0
    female_with_most_hours = None

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_with_most_hours = name

    return female_with_most_hours, max_hours

# Call the function to find the female worker with the most hours
female_worker, max_hours = find_female_with_most_hours(work_hours)

# Calculate her payment (assuming $20 per hour)
payment = max_hours * 20

print(f"The female worker that worked the most hours is {female_worker} and she should be paid ${payment}")

The female worker that worked the most hours is Penny and she should be paid $18400


In [8]:
import numpy as np
pattern = np.array([[1 ,1] , [2 ,2]])
matrix =np.vstack([np.hstack([pattern]*2)]*2 + [np.hstack([pattern]*2)])
print(matrix)

[[1 1 1 1]
 [2 2 2 2]
 [1 1 1 1]
 [2 2 2 2]
 [1 1 1 1]
 [2 2 2 2]]


In [9]:
import numpy as np
matrix_5x5 = np.array([[1, 1, 1, 1, 1],
                       [2, 2, 2, 2, 2],
                       [1, 1, 1, 1, 1],
                       [2, 2, 2, 2, 2],
                       [1, 1, 1, 1, 1]])
matrix_Nx5 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12],
                       [13, 14, 15]])
dot_product = np.dot(matrix_5x5, matrix_Nx5)
print("Dot Product Matrix:")
print(dot_product)
print("Shape of Dot Product Matrix:", dot_product.shape)

Dot Product Matrix:
[[35 40 45]
 [70 80 90]
 [35 40 45]
 [70 80 90]
 [35 40 45]]
Shape of Dot Product Matrix: (5, 3)
